### ISSUE TITLE
svg-baker-runtime?

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [JetBrains/svg-mixer#36]
Hello again :)

May I ask where the [svg-baker-runtime](https://www.npmjs.com/package/svg-baker-runtime) NPM package got moved to? I'm trying to, uh, track down license information for it, too, haha.

**Comment by kisenka** [comment]
You can check svg-baker-runtime license at NPM package page:
![image](https://user-images.githubusercontent.com/2714771/45767533-18d14a00-bc43-11e8-9735-118d12b2e897.png)

**Comment by Bosch-Eli-Black** [comment]
Thanks for the reply, @kisenka.

I saw the MIT license on the NPM package page, but my understanding is that in order for the code to be properly MIT licensed, the full MIT license text needs to be included in the repository.

Anyway, you mentioned in another issue that you're planning to move the `svg-sprite-loader` project over to using the `svg-mixer` package, so I think it'd probably be better if I just wait for that.

Thanks again :)
