### ISSUE TITLE
Default config won't allow custom Sprite Class

### ISSUE THREAD

**Issue by GiGaJo** [JetBrains/svg-mixer#37]
https://github.com/JetBrains/svg-mixer/blob/84fe34cb40ff240454627764ad0ae03d805b9fda/packages/svg-mixer/lib/compiler.js#L58

I tried the [extending example](https://github.com/JetBrains/svg-mixer/tree/master/packages/svg-mixer#extending) but it always was replaced by the base class (mixer.Sprite) because of the default config 'spriteType' which only allows 'classic' and 'stack' as defined [here](https://github.com/JetBrains/svg-mixer/blob/84fe34cb40ff240454627764ad0ae03d805b9fda/packages/svg-mixer/schemas/defs.js#L8).

Maybe add a third option 'custom' which will not replace the Sprite class.

**Comment by kisenka** [comment]
@GiGaJo thanks for reporting! Fixed in `svg-mixer@2.3.4`
