### ISSUE TITLE
extract-svg-sprite-webpck-plugin npm package missing files.

### ISSUE THREAD

**Issue by vicvinc** [JetBrains/svg-mixer#39]
![image](https://user-images.githubusercontent.com/3063949/46185993-f7412400-c30e-11e8-96e3-f0765ad662ac.png)

![image](https://user-images.githubusercontent.com/3063949/46185997-032ce600-c30f-11e8-8a4d-0b10c47e49f9.png)

currently, the version is 3.2.0. but installed files didn't match.

**Comment by kisenka** [comment]
@vicvinc thanks for reporting! Fixed in extract-svg-sprite-webpack-plugin@0.3.3
