### ISSUE TITLE
Wrong index for existing icon reference due to Async operation 

### ISSUE THREAD

**Issue by esjs** [JetBrains/svg-mixer#43]
I'm using https://github.com/kisenka/svg-sprite-loader in one of our projects which uses this project under the hood. Issue that I have is that sometimes on build I get incorrect set of icons (when there are duplicates).

So after debugging, I've spotted the source of problem. The issue is caused by incorrect index of icon in array due to asynchronous operations. I have not found contributing guide so I'll describe issue here

If you would look at source code lines 51-55
https://github.com/JetBrains/svg-mixer/blob/v1/packages/svg-baker/lib/compiler.js#L51
you will see that it is storing index of current element in array.

Later, there is an asynchronous operation
https://github.com/JetBrains/svg-mixer/blob/v1/packages/svg-baker/lib/compiler.js#L57
where this index is used
https://github.com/JetBrains/svg-mixer/blob/v1/packages/svg-baker/lib/compiler.js#L64
we update item be previously stored index and than call sort which can totally change order of items and all other "addSymbol" calls which have "existingIndex" already calculated but wait for their async task to end can end up with wrong index.

My proposal is to move lines 51 through 55 inside of "SpriteSymbol.create" in current code it would be line 58 or even better on line 63, so we don't execute code that won't be used (in case it's nonexisting icon). By doing this we can guarantee that index is calculated correctly when it is used and nothing can mess it up.

Hope my point is clear, unfortunately it's really hard to create test case to reproduce this issue, but I think you would agree that my arguments makes sense.

Thank you in advance,
Vladimir

**Comment by kisenka** [comment]
@esjs hi! Thanks for detailed report. Could you please make a pull request with described modifications?

**Comment by machadoum** [comment]
Hi, @kisenka  

Do you have any updates on it? This bug is affecting `svg-sprite-loader`. 
https://github.com/kisenka/svg-sprite-loader/issues/328

Thank you for your time.

**Comment by kisenka** [comment]
Fixed in `svg-sprite-loader@4.1.6`, please update
