### ISSUE TITLE
extract-svg-sprite-webpack-plugin couldn't work with require.context

### ISSUE THREAD

**Issue by Frezc** [JetBrains/svg-mixer#48]
reproduce here: https://github.com/Frezc/extract-svg-plugin-reproduce

**Comment by rosscreighton** [comment]
@Frezc did you make any headway on this? I'm working on the same problem.

**Comment by Frezc** [comment]
@rosscreighton no, but if you don't need extract mode, try https://github.com/kisenka/svg-sprite-loader .

**Comment by kisenka** [comment]
@Frezc fixed in `extract-svg-sprite-webpack-plugin@0.7.3`
