### ISSUE TITLE
postcss-move-props-to-bg-image-query doesn't work.

### ISSUE THREAD

**Issue by wujekbogdan** [JetBrains/svg-mixer#49]
here's my PostCSS config:

``` javascript
const postCssAutoprefixer = require('autoprefixer');
const moveProps = require('postcss-move-props-to-bg-image-query');

module.exports = () => ({
  plugins: [
    moveProps(),
    postCssAutoprefixer(),
  ],
});
```

Here's my CSS:

``` css
.test {
  background-image: url('../img/ico.svg');
  transform: translateX(20);
  -svg-fill: red;
}
```

I see that the file is processed by PostCSS, because vendor prefixes are added by autoprefixer, but `moveProps()` doesn't seem to work. I still see the `-svg-fill: red;` entry in the output file (which shouldn't be there) and I don't see any query parameters after `'../img/ico.svg'` (which should be added).

I also tried to pass the `transform` parameter as follows:

```
module.exports = () => ({
  plugins: [
    moveProps({
      transform(obj) {
        console.log(obj);
      },
    }),
    postCssAutoprefixer(),
  ],
});
```

But I can't see any output in the console, so it looks like the transformation callback is not even called.

---
webpack: ^4.20.0
postcss-loader: ^3.0.0

**Comment by wujekbogdan** [comment]
It turned out that `postcss-move-props-to-bg-image-query` works fine, but there's a bug in the documentation. The documentation says that the default prefix is `-svg-` which is not true - the default prefix is `-svg-mixer-`.

**Comment by kisenka** [comment]
@wujekbogdan you're right, docs [were updated](https://github.com/JetBrains/svg-mixer/commit/9a68b9ceacb011430691e4d7f41d6f72258cbbff)
