### ISSUE TITLE
[Docs] the documentation for the `match` property is misleading. 

### ISSUE THREAD

**Issue by wujekbogdan** [JetBrains/svg-mixer#51]
The [documentation](https://github.com/JetBrains/svg-mixer/tree/master/packages/postcss-move-props-to-bg-image-query#configuration) for the `match` property says:

> Filter which declarations should be transformed. Could be a string (glob pattern), RegExp or array of them.

Here's the default config from the plugin's source:

``` javascript
const defaultConfig = {
  match: '-svg-mixer-*',
  computeCustomProps: false,
  transform: ({ name, value }) => ({
    name: name.replace(/^-svg-mixer-/, ''),
    value
  })
};
```

So if we change only the `match` property then the plugin will not work - the `math` property must be changed together with the `transform` property because they both have the `-svg-mixer-` string hardcoded.

So you should either update the docs or pass the math property somehow to the `transform` callback as a parameter.

**Comment by kisenka** [comment]
docs [were updated](https://github.com/JetBrains/svg-mixer/commit/9a68b9ceacb011430691e4d7f41d6f72258cbbff)
