### ISSUE TITLE
Transformations are not applied when using dart sass instead of node-sass

### ISSUE THREAD

**Issue by wujekbogdan** [JetBrains/svg-mixer#52]
I've been trying to migrate one of my project from `node-sass` to `sass` (the official dart-based sass implementation).  After replacing `node-sass` with `sass` the transformations are not applied by `svg-transform-loader`.

**Comment by wujekbogdan** [comment]
I was trying to resolve the issue trying various things, even these ones that dont' seem to make much sense. One of them was to try different prefixes for `-svg` properties. After I changed the prefix from `-svg-` to `svg` it started to work!

This is my postcss config:

``` js
const moveProps = require('postcss-move-props-to-bg-image-query');

module.exports = () => ({
  plugins: [
    moveProps({
      match: 'svg-*',
      transform: ({ name, value }) => ({
        name: name.replace(/^svg-/, ''),
        value,
      }),
    }),
  ],
});
```

If the prefix contains `--` or `-` in front of it then transformations are not applied. Does it make any sense?

**Comment by kisenka** [comment]
@wujekbogdan have no idea to be honest, could you please create a demo with demonstration of described issue?

**Comment by kisenka** [comment]
@wujekbogdan ping. If it still actual - please create a demo. If not close the issue then.
