### ISSUE TITLE
extract-svg-sprite-webpack-plugin | wrong behaviour when one icon is required in two source css files

### ISSUE THREAD

**Issue by AlexDubok** [JetBrains/svg-mixer#54]
When one icon is required in two source css files, only one occurrence of it will be replaced with sprite id in the result css. 
I think that there should be an array of modules assigned to one symbol instead of just one module.
What are your thoughts?

**Comment by kisenka** [comment]
Looks like this issue was fixed by your [PR](https://github.com/JetBrains/svg-mixer/pull/56) :)
