### ISSUE TITLE
usageIdSuffix in spriteConfig

### ISSUE THREAD

**Issue by MatzeDS** [JetBrains/svg-mixer#60]
Missing "p" in sriteConfig at replacement-generator.js
`const { filename, emit, spriteType, sriteConfig } = config;`

**Comment by vchrm** [comment]
@kisenka Yep, confirming it.

In our case it also somehow crashes `stats.toString()` call on webpack's Stats Object with `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined`.

Fixing the typo in `extract-svg-sprite-webpack-plugin/lib/utils/replacement-generator.js` fixes the error.

**Comment by kisenka** [comment]
Fixed in #69
