### ISSUE TITLE
New v1 release

### ISSUE THREAD

**Issue by escaton** [JetBrains/svg-mixer#67]
@kisenka Could you please cut new v1 release with changes from #61 ?

**Comment by escaton** [comment]
@kisenka ping
and not to ask twice: please cut another release of svg-sprite-loader with updated dependency.

**Comment by escaton** [comment]
@kisenka ping

**Comment by escaton** [comment]
@kisenka ping

**Comment by escaton** [comment]
@kisenka ping

**Comment by btd** [comment]
@kisenka PING

**Comment by escaton** [comment]
@a-krasilnikov sorry for disturbing you but i can't reach to your colleague. Could you please help somehow?

**Comment by kisenka** [comment]
@escaton done, `svg-sprite-loader@4.2.0`
