### ISSUE TITLE
Invalid CSS file when SVG images have conflicting file names

### ISSUE THREAD

**Issue by vchrm** [JetBrains/svg-mixer#70]
After a successful integration of extract-svg-sprite-webpack-plugin to our project  I carefully checked the resulting CSS file one last time.

I found a few items resolved like this:
`background: url(/___b5f499a2d2cab88d293d5e0c335ef204___)`

I investigated the issue and the problem is that when you use two SVG images with the same file name (no matter the directory), one of them gets resolved properly and the second one ends this way.

What I find the most dangerous is that the compilation process does not throw any errors so you won't know until someone notices. (In our case we use extract-svg-sprite-webpack-plugin in production only so we would see it too late.)

Shouldn't that throw an error?

**Comment by vchrm** [comment]
Okay so the core of problem seems to be not in conflicting file names but in conflicting symbol ids. Since the default to `symbolId` parameter is `"[name]"`, in this default case the conflicts happen when file names are the same.

Fortunately that also brings us to the resolution: when you use a different `symbolId` parameter like
`"[name]-[hash]"`, things get much better. However, this won't save you when you have two copies of the same file with the same file name in two different directories.

So we ended up with `symbolId` set to custom callback calculating sha1 hash from the SVG file's path. No more conflicts.

**Comment by kisenka** [comment]
You can use any pattern from [loader-utils#interpolateName](https://github.com/webpack/loader-utils#interpolatename), eg. `[path]-[name]-[hash]` in your case. But you're right, plugin should replace placeholder properly even if it points to different files.

**Comment by kisenka** [comment]
@vchrm added warning about several symbols with duplicating ids in extract-svg-sprite-webpack-plugin@0.7.2
