### ISSUE TITLE
[webpack] css-loader v4.2 breaks svg-mixer

### ISSUE THREAD

**Issue by makge** [JetBrains/svg-mixer#93]
I use a postcss-move-props-to-bg-image-query plugin.
After upgrade css-loader from 3.6 to 4.2 the plugin doesn't work anymore.

css-loader v3.6: Ok!
![css-loader-v3 6](https://user-images.githubusercontent.com/47385441/90191301-097cbc00-ddda-11ea-8a7b-0c61df9bc3f5.png)

css-loader v4.2: Fail!
![css-loader-v4 2](https://user-images.githubusercontent.com/47385441/90191351-2618f400-ddda-11ea-8caf-dcef27b12b1a.png)

**Comment by coreyworrell** [comment]
Noticing this as well. 

```
data:image/svg+xml;base64,PHN2...dmc+#fff
```

**Comment by g4g1** [comment]
Same here :/

**Comment by lada** [comment]
After several hours, I've found a workaround:

1) don't use the `#` symbol in your css:

```css
.img {
  background-image: url('./img.svg?fill=fff');
}
```

2) Include the svg-transform-loader like this:

```js
{
  loader: 'svg-transform-loader',
  options: {
    transformQuery(query) {
      if (query.fill) {
        query.fill = `#${query.fill}`;
      }
    },
  },
},
```

Hope it helps.

**Comment by g4g1** [comment]
Looks like its ok in css-loader v5.0.2
https://github.com/webpack-contrib/css-loader/pull/1261

**Comment by makge** [comment]
Yes, it works now with css-loader v5.0.2
Thanks g4g1!
